---
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (fedora)
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Fedora"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost # running the playbook against the host machine
  connection: local #use local connection -> no ssh
  become: true # using sudo
  tasks:

    ## Including the variables which might be distribution specific
    - name: Including distribution specific variables
      include_vars: "{{ ansible_distribution }}.yml"
      tags: always

        ## Including the workstation variables
    - name: Including workstation specific variables
      include_vars: "workstation.yml"
      tags: always,workstation

        ## User configs
    - import_tasks: tasks/users/mose.yml

      ## Installing python (needed for setup)
    - import_tasks: tasks/software/python.yml

      ## desktop environments
      ### Gnome
    - include_tasks: tasks/desktop_environments/gnome/appearance.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/keybindings.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/nautilus.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/peripherals.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/power.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/shell-settings.yml
      tags: always
      when: gnome is defined and gnome == true

    - include_tasks: tasks/desktop_environments/gnome/terminal.yml
      tags: always
      when: gnome is defined and gnome == true

      ### awesome
    - include_tasks: tasks/desktop_environments/awesome/config.yml
      tags: always
      when: awesome is defined and awesome == true

    - include_tasks: tasks/desktop_environments/awesome/software.yml
      tags: always
      when: awesome is defined and awesome == true

      ### i3
    - include_tasks: tasks/desktop_environments/i3/config.yml
      tags: always
      when: i3 is defined and i3 == true

    - include_tasks: tasks/desktop_environments/i3/software.yml
      tags: always
      when: i3 is defined and i3 == true

      ### sway
    - include_tasks: tasks/desktop_environments/sway/config.yml
      tags: always
      when: sway is defined and sway == true

    - include_tasks: tasks/desktop_environments/sway/software.yml
      tags: always
      when: sway is defined and sway == true

        ## enable repositories
    - import_tasks: tasks/system_setup/repositories.yml

      # Software installation
    - import_tasks: tasks/software/codecs.yml
    - import_tasks: tasks/software/package_utilities.yml

      ## add flatpak support and flathub remote
    - import_tasks: tasks/software/flatpak.yml

      ### installing flatpak software
    - import_tasks: tasks/software/anki.yml
    - import_tasks: tasks/software/audacity.yml
    - import_tasks: tasks/software/bitwarden.yml
    - import_tasks: tasks/software/discord.yml
    - import_tasks: tasks/software/ferdi.yml
    - import_tasks: tasks/software/gnome_power_statistics.yml
    - import_tasks: tasks/software/pavucontrol.yml
    - import_tasks: tasks/software/signal.yml
    - import_tasks: tasks/software/spotify.yml
    - import_tasks: tasks/software/synology.yml
    - import_tasks: tasks/software/thunderbird.yml
    - import_tasks: tasks/software/vlc.yml
    - import_tasks: tasks/software/zoom.yml

    - import_tasks: tasks/software/alacritty.yml
    - import_tasks: tasks/software/moneydance.yml
    - import_tasks: tasks/software/polybar.yml
    - import_tasks: tasks/software/rambox.yml
    - import_tasks: tasks/software/ranger.yml
    - import_tasks: tasks/software/syncthing.yml
    - import_tasks: tasks/software/urxvt.yml
    - import_tasks: tasks/software/zsh.yml
