---
- hosts: localhost # running the playbook against the host machine
  connection: local #use local connection -> no ssh
  become: true # using sudo

  tasks:
  - name: install htop and nvim
    package:
      name:
        - htop
        - neovim

  - name: copy wallpaper file
    copy:
      src: files/Horizons_Single.jpg
      dest: /usr/share/backgrounds/Horizons_Single.jpg
      owner: root
      group: root

  - name: set wallpaper
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Horizons_Single.jpg'"


  - name: set wallpaper position
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
