---
- hosts: localhost # running the playbook against the host machine
  connection: local #use local connection -> no ssh
  become: true # using sudo

  tasks:
  - name: install python environment
    package:
      name:
        - python3-numpy
        - python3-scipy
        - python3-matplotlib
        - python3-ipython
        - python3-pandas
        - python3-sympy
        - python3-nose
        - atlas-devel
        - python3-psutil

  - name: install htop and nvim
    package:
      name:
        - htop
        - neovim

  - name: copy wallpaper file
    copy:
      src: files/Horizons_Single.jpg
      dest: /usr/share/backgrounds/Horizons_Single.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Horizons_Single.jpg'"


  - name: set wallpaper position
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc
    copy:
      src: files/bashrc
      dest: /home/mose/.bashrc
      owner: mose
      group: mose

  - name: enable git prompt
    copy:
      src: files/git-prompt.sh
      dest: /home/mose/.git-prompt.sh
      owner: mose
      group: mose
