---

- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (fedora)
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Fedora"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost # running the playbook against the host machine
  connection: local #use local connection -> no ssh
  become: true # using sudo

  tasks:
  - name: install python environment
    package:
      name:
        - python3-numpy
        - python3-scipy
        - python3-matplotlib
        - python3-ipython
        - python3-pandas
        - python3-sympy
        - python3-nose
        - atlas-devel
        - python3-psutil
        - python3-notebook

  - name: installing qutip with pip
    pip:
      name:
        - qutip

  - name: install htop and nvim
    package:
      name:
        - htop
        - neovim

  - name: copy wallpaper file
    copy:
      src: files/Horizons_Single.jpg
      dest: /usr/share/backgrounds/Horizons_Single.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Horizons_Single.jpg'"


  - name: set wallpaper position
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: users | mose | create personal config directories
    tags: dotfiles,dotfiles-mose
    file:
      path: /home/mose/{{ item.dir }}
      state: directory
      owner: mose
      group: mose
      mode: 0700
    with_items:
      - { dir: .config }
      - { dir: .config/nvim }
      - { dir: .local }
      - { dir: .local/share }
      - { dir: .local/share/applications }

  - name: users | mose | copy personal config files
    copy:
      src: users/mose/{{ item.src }}
      dest: /home/mose/{{ item.dest }}
      owner: mose
      group: mose
      mode: 0600
    with_items:
      - { src: 'git-prompt.sh', dest: '.git-prompt.sh'}
      - { src: 'bashrc', dest: '.bashrc'}
      - { src: 'vimrc', dest: '.vimrc' }

  - name: users | mose | create symbolic links
    file:
      src: /home/mose/{{ item.src }}
      dest: /home/mose/{{ item.dest }}
      state: link
    with_items:
      - { src: '.vimrc', dest: '.config/nvim/init.vim'}
