# Wallpaper
  - name: copy wallpaper file
    copy:
      src: files/wallpaper/wallpaper.jpg
      dest: /usr/share/backgrounds/wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/wallpaper.jpg'"

  - name: set wallpaper position
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

# profile picture
  - name: verify profile picture
    stat:
      path: /var/lib/AccountsService/icons/mose
    register: profile_picture

  - name: copy profile picture
    become: true
    copy:
      src: files/users/mose/mose
      dest: /var/lib/AccountsService/icons/mose
      force: true
      owner: root
      group: root
    #when: not profile_picture.stat.exists

  - name: set profile picture
    become: true
    lineinfile:
      path: /var/lib/AccountsService/users/mose
      regexp: '^Icon='
      line: 'Icon=/var/lib/AccountsService/icons/mose'

# desktop time and calendar settings
  - name: gnome | appearance | desktop clock settings
    tags: gnome,calendar,time
    become_user: mose
    dconf:
      key: /org/gnome/desktop/interface/{{ item.key }}
      value: "{{ item.value}}"
    with_items:
      - { key: "clock-show-seconds", value: "false" }
      - { key: "clock-show-weekday", value: "true" }
      - { key: "enable-hot-corners", value: "true" }

  - name: gnome | appearance | calendar settings
    tags: gnome,calendar,time
    become_user: mose
    dconf:
      key: /org/gnome/desktop/calendar/show-weekdate
      value: "true"
