# Wallpaper
  - name: copy wallpaper file
    copy:
      src: files/wallpaper/Horizons_Single.jpg
      dest: /usr/share/backgrounds/Horizons_Single.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Horizons_Single.jpg'"


  - name: set wallpaper position
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

# profile picture
  - name: verify profile picture
    stat:
      path: /var/lib/AccountsService/icons/mose
    register: profile_picture

  - name: copy profile picture
    become: true
    copy:
      src: files/users/mose/mose
      dest: /var/lib/AccountsService/icons/mose
      force: true
      owner: root
      group: root
    #when: not profile_picture.stat.exists

  - name: set profile picture
    become: true
    lineinfile:
      path: /var/lib/AccountsService/users/mose
      regexp: '^Icon='
      line: 'Icon=/var/lib/AccountsService/icons/mose'
