# Wallpaper
  - name: copy wallpaper file
    copy:
      src: files/wallpaper/Horizons_Single.jpg
      dest: /usr/share/backgrounds/Horizons_Single.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Horizons_Single.jpg'"


  - name: set wallpaper position
    become_user: mose
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
