# Keybindings (get using 'dconf dump / > settings.txt')
  - name: gnome | keybindings | set custom-keybindings
    tags: gnome,keybindings
    become_user: mose
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

  - name: gnome | keybindings | setting terminal keybinding
    tags: gnome,keybindings
    become_user: mose
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Terminal'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super><Enter>'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'gnome-terminal'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'Tmux'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Primary><Alt>m'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'gnome-terminal -e \"tmux new -A -s main\"'" }

  - name: gnome | keybindings | Setting workspace keybindings
    tags: gnome,keybindings,workspaces
    become: true
    tasks:
      - name: copy config file containing workspace keybindings
        copy:
          src: users/mose/dconf/workspace-settings
          path: /etc/dconf/db

      - name: update dconf
        shell: dconf update
