# Keybindings
  - name: gnome | keybindings | set custom-keybindings
    tags: gnome,keybindings
    become_user: mose
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

  - name: gnome | keybindings | setting terminal keybinding
    tags: gnome,keybindings
    become_user: mose
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Terminal'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Primary><Alt>t'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'gnome-terminal'" }
