- name: Python | Install essential packages
  tags: python
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - python3-pip
      - pipx
    state: present
# vim: ft=yaml.ansible
