#!/usr/bin/env sh

# Print the name of the first tmux session that has no clients attached.
SESSION=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' 2>/dev/null | grep 'not attached$' | tail -n 1 | cut -d '|' -f1)

echo $SESSION
tmux attach -t $SESSION 2> /dev/null || tmux
# tmux attach -t "$SESSION" || tmux new
