- name: i3 config files
  block:
    - name: desktop environment | i3 | create i3 config directories
      tags: dotfiles,dotfiles-mose
      file:
        path: /home/mose/{{ item.dir }}
        state: directory
        owner: mose
        group: mose
        mode: 0700
      with_items:
        - { dir: .config }
        - { dir: .config/autorandr}
        - { dir: .config/i3}
        - { dir: .config/rofi}
        - { dir: .local/share/fonts}

    - name: desktop environment | i3 | copy i3 config files
      tags: dotfiles,dotfiles-mose
      copy:
        src: users/mose/{{ item.src }}
        dest: /home/mose/{{ item.dest }}
        owner: mose
        group: mose
        mode: 0600
      with_items:
        - { src: 'i3.config', dest: '.config/i3/config'}
        - { src: 'rofi/config.rasi', dest: '.config/rofi/config.rasi'}
        - { src: 'autorandr/', dest: '.config/autorandr/'}
        - { src: 'fonts/', dest: '.local/share/fonts/'}
        - { src: 'thinkpad/Xresources', dest: '.Xresources'}
        - { src: 'thinkpad/profile', dest: '.profile'}

- name: i3 wallpaper
  tags: wallpaper,i3
  block:
    - name: copy wallpaper file
      copy:
        src: files/wallpaper/wallpaper.jpg
        dest: /usr/share/backgrounds/wallpaper.jpg
        owner: root
        group: root

- name: urxvt extensions
  tags: urxvt,urxvt-extensions,i3
  block:
    - name: desktop environment | i3 | creating urxvt extensions folders
      file:
        path: /home/mose/{{ item.dir }}
        state: directory
        owner: mose
        group: mose
        mode: 0700
      with_items:
        - { dir: .urxvt}
        - { dir: .urxvt/ext}

    - name: desktop environment | i3 | copy urxvt extensions
      copy:
        src: users/mose/{{ item.src }}
        dest: /home/mose/{{ item.dest }}
        owner: mose
        group: mose
        mode: 0600
      with_items:
        - { src: 'urxvt/ext/', dest: '.urxvt/ext/'}
