# Installing required software packages specific to i3wm
  - name: i3-specific software
    tags: i3
    package:
      name:
        - i3
        - i3blocks
        - dunst # notification deamon
        - acpi # power management tool needed for i3blocks
        - arandr # monitor settings
        - autorandr
        - blueman # bluetooth
        - brightnessctl # for adjusting brightness with multimedia keys
        - feh # for background wallpaper
        - lxpolkit # authentification manager
        - playerctl # keybinding for multimedia
        - rofi # program lancher
        - sysstat # for cpu usage in i3blocks
        - xclip # enabling copy on X-server
        - xcompmgr # compositor for transparency
        - xprop # used to identify class of programs
      state: latest

