#---
#- hosts: localhost
#  tags: always
#  become: true
#  tasks:
    - name: system setup | repositories | Importing rpm-fusion (free/non-free) key
      tags: repository, gpg-key, rpm-fusion
      rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      when: ansible_distribution == 'Fedora'

    - name: system setup | repositories | enable RPM Fusion repository on Fedora
      tags: repository, rpm-fusion
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
      when: ansible_distribution == 'Fedora'

    - name: system setup | repositories | enable VSCode repository on Fedora
      tags: repository,vscode
      rpm_key:
        key: "https://packages.microsoft.com/keys/microsoft.asc"
      when: ansible_distribution == 'Fedora' and vscode is defined and vscode == true

    - name: TLP repo
      block:
        - name: system setup | repositories | Importing TLP GPG key
          tags: repository, gpg-key, tlp
          rpm_key:
            key: https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-{{ansible_distribution_major_version}}-primary
            state: present
          when: ansible_distribution == 'Fedora'

        - name: system setup | repositories | enable ThinkPad Extras repository on Fedora
          tags: repository, tlp
          dnf:
            name: "{{ item }}"
            state: present
            disable_gpg_check: true
          loop:
            - https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ansible_distribution_major_version}}.noarch.rpm
          when: ansible_distribution == 'Fedora'

        - name: system setup | repositories | copy tlp config
          tags: dotfiles,dotfiles-mose,tlp
          copy:
            src: users/mose/tlp.conf
            dest: /etc/tlp.conf
            owner: mose
            group: mose
            mode: 0600
      when: tlp is defined and tlp == true
