- name: Software | vscode
  tags: vscode
  when: vscode is defined and vscode is true
  block:
    - name: Software | vscode | Install VSCode (Fedora)
      tags: repository,vscode
      when: ansible_distribution == 'Fedora'
      block:
        - name: Software | vscode | Enable VSCode repository | adding key
          ansible.builtin.rpm_key:
            key: "https://packages.microsoft.com/keys/microsoft.asc"
        - name: Software | vscode | Enable VSCode repository | adding repository
          ansible.builtin.shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
        - name: Software | vscode | Installing package
          ansible.builtin.package:
            name:
              - code
            state: present

    - name: Software | vscode | Installing package (Ubuntu)
      tags: repository,vscode
      become: true
      become_user: root
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        deb: https://update.code.visualstudio.com/latest/linux-deb-x64/stable

    - name: Software | vscode | create config directory
      tags: dotfiles,dotfiles-mose
      ansible.builtin.file:
        path: /home/mose/.config/{{ item.dir }}
        state: directory
        owner: mose
        group: mose
        mode: "0700"
      with_items:
        - { dir: Code }
        - { dir: Code/User }

    - name: Software | vscode | copy config file
      ansible.builtin.copy:
        src: vscode/{{ item.src }}
        dest: /home/mose/.config/Code/User/{{ item.dest }}
        owner: mose
        group: mose
        mode: "0600"
      with_items:
        - { src: "keybindings.json", dest: "keybindings.json" }
        - { src: "settings.json", dest: "settings.json" }
        - { src: "extensions.txt", dest: "extensions.txt" }

    - name: Software | vscode | installing extensions
      become: true
      become_user: mose
      ansible.builtin.shell: while read p; do code --install-extension "${p}"; done </home/mose/.config/Code/User/extensions.txt
# vim: ft=yaml.ansible
