# Config files
- name: config files
  block:
    - name: users | mose | tmux
      tags: dotfiles,dotfiles-mose,tmux
      block:
        - name: users | mose | tmux | tmux folder
          file:
            path: /home/mose/{{ item.dir }}
            state: directory
            owner: mose
            group: mose
            mode: 0700
          with_items:
            - { dir: .tmux }

        - name: users | mose | tmux | tmux config
          copy:
            src: users/mose/{{ item.src }}
            dest: /home/mose/{{ item.dest }}
            owner: mose
            group: mose
            mode: 0600
          with_items:
            - { src: 'tmux/tmux.conf', dest: '.tmux.conf'}

        - name: users | mose | tmux | copy executable files
          copy:
            src: users/mose/{{ item.src }}
            dest: /home/mose/{{ item.dest }}
            owner: mose
            group: mose
            mode: a+x
          with_items:
            - { src: 'tmux/tmux-first-unattached-session', dest: '.tmux/'}

        - name: users | mose | tmux | clone tmux plugin manager repository
          git:
            repo: https://github.com/tmux-plugins/tpm.git
            dest: /home/mose/.tmux/plugins/tpm
          become: yes
          become_user: mose
      when: tmux is defined and tmux == true

    - name: users | mose | create personal config directories
      tags: dotfiles,dotfiles-mose
      file:
        path: /home/mose/{{ item.dir }}
        state: directory
        owner: mose
        group: mose
        mode: 0700
      with_items:
        - { dir: .config }
        - { dir: .config/autostart }
        - { dir: .local }
        - { dir: .local/share }
        - { dir: .local/share/applications }

    - name: users | mose | copy personal config files
      tags: dotfiles,dotfiles-mose
      copy:
        src: users/mose/{{ item.src }}
        dest: /home/mose/{{ item.dest }}
        owner: mose
        group: mose
        mode: 0600
      with_items:
        - { src: 'git-prompt.sh', dest: '.git-prompt.sh'}
        - { src: 'bashrc', dest: '.bashrc'}
        - { src: 'vimrc', dest: '.vimrc' }
        - { src: 'gitconfig', dest: '.gitconfig' }

    - name: users | root | link nvim config directory
      tags: dotfiles,dotfiles-root,nvim
      block:

      - name: users | root | create config folder
        file:
          path: /root/{{ item.dir }}
          state: directory
          owner: mose
          group: mose
          mode: 0700
        with_items:
          - { dir: .config/nvim }

      - name: users | root | create symbolic links
        file:
          src: /home/mose/{{ item.src }}
          dest: /root/{{ item.dest }}
          state: link
          force: yes
        with_items:
          # - { src: '.vimrc', dest: '.config/nvim/init.vim'}
          - { src: '.config/nvim', dest: '.config/nvim'}

  when: personal_config is defined and personal_config == true
