- name: software | anki | install package
  tags: packages,flatpak,anki,workstation-packages
  become_user: mose
  flatpak:
    name: net.ankiweb.Anki
    method: system
    state: present
  when: anki is defined and anki == true
