- name: software | audacity | install package
  tags: packages,flatpak,audacity,workstation-packages
  become_user: mose
  flatpak:
    name: org.audacityteam.Audacity
    method: user
    state: present
