- name: software | ferdi | install package
  tags: packages,flatpak,ferdi,workstation-packages
  become_user: mose
  flatpak:
    name: com.getferdi.Ferdi
    method: system
    state: present
  when: ferdi is defined and ferdi == true
