- name: software | gnome power statistics | install package
  tags: packages,flatpak,anki,workstation-packages
  become_user: mose
  flatpak:
    name: org.gnome.PowerStats
    method: system
    state: present
