- name: software | gnome power statistics | install package
  tags: packages,flatpak,gnome-power-statistics,workstation-packages
  become_user: mose
  flatpak:
    name: org.gnome.PowerStats
    method: system
    state: present
  when: gnome_power_statistics is defined and gnome_power_statistics == true
