- name: download and install moneydance
  block:
   - name: Create a Directory /opt/moneydance
     become: yes
     file:
       path: /opt/moneydance
       state: directory
       mode: 0755
       owner: mose
       group: mose
   - name: Download moneydance using get_url
     become: yes
     get_url:
       url: https://infinitekind.com/stabledl/current/moneydance_linux_amd64.sh
       dest: /opt/moneydance/moneydance_linux_amd64.sh
       mode: 0755
       group: mose
       owner: mose
       checksum: sha512:8d36a9464c0eaa53168b361bb231c82e474290a19c1a396753b26e34a6f635e42a4ec005d7f8ffdb5e882cbc1fd20920d19eb7c72ad4706bf66051f849be44e1
   - name: Install moneydance
     shell:
       cmd: bash moneydance_linux_amd64.sh
       chdir: /opt/moneydance
       creates: /opt/moneydance/Moneydance
   - name: Create desktop file
     copy:
       dest: "/usr/local/share/applications/moneydance.desktop"
       content: |
         [Desktop Entry]
         Version=1.0
         Type=Application
         Terminal=false
         Exec=/opt/moneydance/Moneydance
         Name=Moneydance
         Icon=/opt/moneydance/resources/moneydance_icon512.png
         Categories=Money-management
         Comment=Money management software
         StartupNotify=true
  when: moneydance is defined and moneydance == true
