# C++ tools
  - name: install C/C++ tools
    package:
      name:
        - lapack-devel
        - gsl-devel
        - make
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        #- libstdc++ # already installed
        #- glibc # already installed
      state: latest

  - name: installing visualisation programms
    package:
      name:
        - okular
        - gimp
        - inkscape
      state: latest

  - name: installing tools
    package:
      name:
        - pavucontrol # sound control
        - htop
        - neovim
        - libnsl # needed for some legacy programms?
        #- libusb # needed for USB devices
        - gnome-tweaks
        - curl
        - rsync
        - screen
        - wget
      state: latest
