# C++ tools
  - name: install C/C++ tools
    package:
      name:
        - lapack-devel
        - gsl-devel
        - make
        - cmake
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        #- libstdc++ # already installed
        #- glibc # already installed
      state: latest

  - name: installing visualisation programms
    package:
      name:
        - okular
        - gimp
        - inkscape
      state: latest

  - name: installing tools
    package:
      name:
        - pavucontrol # sound control
        - htop
        - neovim
        - cronie # for crontabs
        - wl-clipboard # needed for copy/paste to the system clipboard with wayland
        - libnsl # needed for some legacy programms?
        #- libusb # needed for USB devices
        - gnome-tweaks
        - curl
        - rsync
        - screen
        - wget
        - langpacks-de # german language pack for libreoffice
        - langpacks-en_GB # british "
      state: latest

  - name: installing TLP for managing laptop battery power
    package:
      name:
        - tlp
        - tlp-rdw
        - akmod-acpi_call
      state: latest
