# C++ tools
  - name: install C/C++ tools
    package:
      name:
        - lapack-devel
        - gsl-devel
        - make
        - cmake
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        - ninja-build
        #- libstdc++ # already installed
        #- glibc # already installed
      state: latest
    when: cpp_tools is defined and cpp_tools == true


  - name: installing visualisation programms
    package:
      name:
        - okular
        - gimp
        - inkscape
      state: latest

  - name: installing tools
    package:
      name:
        - htop
        - cronie # for crontabs
        - wl-clipboard # needed for copy/paste to the system clipboard with wayland
        - libnsl # needed for some legacy programms?
        #- libusb # needed for USB devices
        - gnome-tweaks
        - curl
        - rsync
        - screen
        - wget
        - fzf # fuzzy search
      state: latest

  - name: installing neovim and dependencies
    tags: nvim
    block:
      - name: Installing programms
        tags: nvim
        package:
          name:
            - neovim
            - nodejs # for plugins (includes npm)
              #- clang-tools-extra # for c++ autocompletion -> not really needed with lua
            - ripgrep
            - python3-flake8
            - python3-black
          state: latest

      - name: Copy config files
        tags: nvim
        copy:
          src: users/mose/nvim
          dest: /home/mose/.config/
          owner: mose
          group: mose
          mode: 0600
    when: nvim is defined and nvim == true

  - name: installing starship
    package:
      name:
        - starship
      state: latest
    when: starship is defined and starship == true


  - name: language packs
    block:
      - name: install language packs
        package:
          name:
            - langpacks-de # german language pack for libreoffice
            - langpacks-en_GB # british "
          state: latest

      - name: remove language packs
        package:
          name:
            - langpacks-en # american english
          state: absent

  - name: installing TLP for managing laptop battery power
    package:
      name:
        - tlp
        - tlp-rdw
        - akmod-acpi_call
      state: latest
    when: tlp is defined and tlp == true
