# C++ tools
  - name: install C/C++ tools
    package:
      name:
        - lapack-devel
        - gsl-devel
        - make
        - cmake
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        - ninja-build
        #- libstdc++ # already installed
        #- glibc # already installed
      state: latest
    when: cpp_tools is defined and cpp_tools == true


  - name: installing visualisation programms
    package:
      name:
        - okular
        - gimp
        - inkscape
      state: latest

  - name: installing tools
    package:
      name:
        - htop
        - cronie # for crontabs
        # - wl-clipboard # needed for copy/paste to the system clipboard with wayland
        - libnsl # needed for some legacy programms?
        #- libusb # needed for USB devices
        # - gnome-tweaks
        - curl
        - rsync
        - screen
        - wget
        - fzf # fuzzy search
        - git
      state: latest

  - name: installing neovim and dependencies
    tags: nvim
    block:
      - name: Installing programms
        tags: nvim
        package:
          name:
            - neovim
            - nodejs # for plugins (includes npm)
            #- clang-tools-extra # for c++ autocompletion -> not really needed with lua
            - ripgrep
            - python3-flake8
            - python3-black
            - python3-mypy
            - python3-virtualenv
          state: latest

      - name: tasks | software | nvim | cloning nvim repo
        tags: dotfiles,dotfiles-mose,nvim
        git:
          repo: https://github.com/mosmuell/nvim_config.git
          dest: /home/mose/.config/nvim
        become: yes
        become_user: mose

      - name: tasks | software | nvim | virtualenv
        tags: nvim,virtualenv,pynvim
        block:
        - name: creating virtualenv folder
          tags: nvim,virtualenv
          file:
            path: /home/mose/{{ item.dir }}
            state: directory
            owner: mose
            group: mose
            mode: 0700
          with_items:
            - { dir: .virtualenvs }

        - name: creating virtual env pynvim
          tags: nvim,pynvim,virtualenv
          pip:
            virtualenv: /home/mose/.virtualenvs/pynvim
            requirements: /home/mose/.config/nvim/pynvim_requirements.txt

    when: nvim is defined and nvim == true

  - name: installing starship
    tags: starship, bash, zsh
    block:
    - name: Download starship installer script
      get_url:
        url: https://starship.rs/install.sh
        dest: /home/mose/starship_installer.sh
    - name: Execute starship installer script
      script: /home/mose/starship_installer.sh -y
    - name: Removing starship installer script
      file:
        path: /home/mose/starship_installer.sh
        state: absent

    when: starship is defined and starship == true


  - name: language packs
    block:
      - name: install language packs
        package:
          name:
            - langpacks-de # german language pack for libreoffice
            - langpacks-en_GB # british "
          state: latest

      - name: remove language packs
        package:
          name:
            - langpacks-en # american english
          state: absent

  - name: installing TLP for managing laptop battery power
    tags: tlp
    package:
      name:
        - tlp
        - tlp-rdw
        # - akmod-acpi_call
      state: latest
    when: tlp is defined and tlp == true
