- name: software | slack | install package
  tags: packages,flatpak,slack,workstation-packages
  become_user: mose
  flatpak:
    name: com.slack.Slack
    method: system
    state: present
  when: slack is defined and slack == true