- name: software | synology | install package
  tags: packages,flatpak,synology,workstation-packages
  become_user: mose
  flatpak:
    name: com.synology.SynologyDrive
    method: system
    state: present
  when: synology is defined and synology == true
