- name: software | thunderbird | install package
  tags: packages,flatpak,thunderbird,workstation-packages
  become_user: mose
  flatpak:
    name: org.mozilla.thunderbird
    method: user
    state: present
