- name: software | vlc | install package
  tags: packages,flatpak,vlc,workstation-packages
  become_user: mose
  flatpak:
    name: org.videolan.VLC
    method: system
    state: present
  when: vlc is defined and vlc == true
