"show line numbers
set number

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces (expandtab) or use tab (noexpandtab)
set noexpandtab

set list
syntax on
set listchars=tab:!·,trail:⎵,nbsp:⎵ " eol:⏎,
set hlsearch

" show current filename
set showtabline=2

" enabling copy and paste
set clipboard=unnamedplus

if has('nvim') " Neovim specific commands
	" echo "Loading nvim settings"

	" Changing listchars color
	hi Whitespace ctermfg=LightGrey
else " Standard vim specific commands
	" echo "Loading vim settings"

	" Changing listchars color
	hi SpecialKey ctermfg=LightGrey

	" copy to clipboard
	xnoremap "+y y:call system("wl-copy", @")<cr>
	nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
	nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p
endif
