- name: Desktop environments | gnome | Wallpaper
  block:
    - name: Desktop environments | gnome | Adding wallpaper
      ansible.builtin.copy:
        src: files/wallpaper/wallpaper.jpg
        dest: /usr/share/backgrounds/wallpaper.jpg
        owner: root
        group: root
        mode: '0644'


    - name: Desktop environments | gnome | Setting wallpaper
      become: true
      become_user: mose
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wallpaper.jpg'"

# profile picture
- name: Desktop environments | gnome | Profile Picture
  become: true
  become_user: mose
  block:
    - name: Desktop environments | gnome | Profile Picture | Verify profile picture
      ansible.builtin.stat:
        path: /var/lib/AccountsService/icons/mose
      register: profile_picture

    - name: Desktop environments | gnome | Profile Picture | Copy profile picture
      become: true
      become_user: root
      ansible.builtin.copy:
        src: profile-picture.png
        dest: /var/lib/AccountsService/icons/mose
        force: true
        owner: root
        group: root
        mode: '0644'
      # when: not profile_picture.stat.exists

    - name: Desktop environments | gnome | Profile Picture | Set profile picture
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /var/lib/AccountsService/users/mose
        regexp: '^Icon='
        line: 'Icon=/var/lib/AccountsService/icons/mose'

# desktop time and calendar settings
- name: Desktop environments | gnome | Clock and Calendar
  tags: calendar,time
  become: true
  become_user: mose
  block:
    - name: Desktop environments | gnome | Clock and Calendar | Clock settings
      community.general.dconf:
        key: /org/gnome/desktop/interface/{{ item.key }}
        value: "{{ item.value }}"
      with_items:
        - { key: "clock-show-seconds", value: "false" }
        - { key: "clock-show-weekday", value: "true" }
        - { key: "enable-hot-corners", value: "true" }

    - name: Desktop environments | gnome | Clock and Calendar | Calendar settings
      community.general.dconf:
        key: /org/gnome/desktop/calendar/show-weekdate
        value: "true"

- name: Desktop environments | gnome | Touchpad
  become: true
  become_user: mose
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/{{ item.key }}
    value: "{{ item.value }}"
  with_items:
    - { key: "tap-to-click", value: "true" }
    - { key: "two-finger-scrolling-enable", value: "true" }

- name: Desktop environments | gnome | Nautilus
  become: true
  become_user: mose
  block:
    - name: Preferences
      community.general.dconf:
        key: /org/gnome/nautilus/preferences/{{ item.key }}
        value: "{{ item.value }}"
      with_items:
        - { key: "default-folder-viewer", value: "'icon-view'" }
        - { key: "migrated-gtk-settings", value: "true" }
        - { key: "search-filter-time-type", value: "'last_modified'" }
        - { key: "show-create-link", value: "true" }
        - { key: "show-delete-permanently", value: "true" }

    - name: File-chooser
      community.general.dconf:
        key: /org/gtk/gtk4/settings/file-chooser/{{ item.key }}
        value: "{{ item.value }}"
      with_items:
        - { key: "show-hidden", value: "true" }
        - { key: "sort-directories-first", value: "true" }

- name: Desktop environments | gnome | Default Applications
  become: true
  become_user: mose
  community.general.dconf:
    key: /org/gnome/desktop/applications/terminal/{{ item.key }}
    value: "{{ item.value }}"
  with_items:
    - { key: "exec", value: "'alacritty'" }

- name: Desktop environments | gnome | Keybindings
  tags: keybindings
  become: true
  become_user: mose
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Terminal'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>Return'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'alacritty'" }

- name: Desktop environments | gnome | Workspaces
  tags: keybindings
  become: true
  become_user: mose
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/shell/keybindings/switch-to-application-1", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-2", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-3", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-4", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-5", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-6", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-7", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-8", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-9", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/preferences/num-workspaces", value: "10" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Super>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Super>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Super>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Super>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5", value: "['<Super>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6", value: "['<Super>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7", value: "['<Super>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8", value: "['<Super>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9", value: "['<Super>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10", value: "['<Super>0']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "['<Super><Shift>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2", value: "['<Super><Shift>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3", value: "['<Super><Shift>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4", value: "['<Super><Shift>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5", value: "['<Super><Shift>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6", value: "['<Super><Shift>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-7", value: "['<Super><Shift>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-8", value: "['<Super><Shift>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-9", value: "['<Super><Shift>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-10", value: "['<Super><Shift>0']" }
    - { key: "/org/gnome/mutter/dynamic-workspaces", value: "false" }
# vim: ft=yaml.ansible
